version: "3"
services:
  # Nginx 1.11.10: https://hub.docker.com/_/nginx/
  web:
    image: nginx:1.11.10
    ports:
      # 将主机的 8080 端口映射到容器的 80 端口
      - 80:80
    links:
      - php
    # 创建一个数据卷，由 ./images/nginx/config => /etc/nginx/conf.d
    volumes:
      - ./nginx/config:/etc/nginx/conf.d:ro

  # PHP 7.1-fpm: https://hub.docker.com/_/php/
  php:
    image: php:7.1-fpm
    volumes:
      - ./apps:/mnt/apps

  # MySQL 5.7: https://hub.docker.com/_/mysql/
  database:
    #image: mysql:5.7
    build: ./php
    # 配置一些环境变量，具体的环境变量细节可以访问上面的网址查看
    environment:
      MYSQL_ROOT_PASSWORD: "rbnewlife"
      MYSQL_USER: "jmesyan"
      MYSQL_PASSWORD: "rbnewlife"
    volumes:
      - ./mysql:/var/lib/mysql

  console:
    build: ./console
    links:
      - php
    tty: true